#!/usr/bin/env python3
"""
Scan docs/videos/* and rebuild docs/assets/data/videos.js with groups per subfolder.

Rules:
- Group title = subfolder name (e.g., RRTN, Templateadapted, Pre-compositedLQ).
- Include files with extensions: .mp4, .webm, .ogv, .avi
- Prefer to sort by filename.

Usage (from repo root):
  python tools/build_videos_js.py --root docs/videos --out docs/assets/data/videos.js
"""

import argparse
from pathlib import Path

PLAYABLE_ORDER = ['.mp4', '.webm', '.ogv', '.avi']
ALLOW_EXT = set(PLAYABLE_ORDER)


def js_escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace("'", "\\'")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default='docs/videos', help='Videos root (default: docs/videos)')
    ap.add_argument('--out', default='docs/assets/data/videos.js', help='Output JS path')
    args = ap.parse_args()

    root = Path(args.root)
    out_path = Path(args.out)
    if not root.exists():
        raise SystemExit(f"Root not found: {root}")
    groups = []
    for group_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
        items = []
        for vid in sorted(group_dir.rglob('*')):
            if vid.is_file() and vid.suffix.lower() in ALLOW_EXT:
                rel = vid.relative_to(root.parent).as_posix()  # path relative to docs/
                title = vid.stem.replace('_', ' ')
                items.append((rel, title))
        if items:
            groups.append((group_dir.name, items))

    # Build JS content
    lines = []
    lines.append('// Auto-generated by tools/build_videos_js.py')
    lines.append('window.videoGroups = [')
    for gi, (gname, items) in enumerate(groups):
        comma_g = ',' if gi < len(groups) - 1 else ''
        lines.append(f"  {{\n    title: '{js_escape(gname)}',\n    items: [")
        for ii, (rel, title) in enumerate(items):
            comma_i = ',' if ii < len(items) - 1 else ''
            lines.append(f"      {{ file: '{js_escape(rel)}', title: '{js_escape(title)}' }}{comma_i}")
        lines.append("    ]\n  }" + comma_g)
    lines.append('];')

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"Wrote {out_path}")


if __name__ == '__main__':
    main()

